{"error_id":"20250619_104538","error_type":"KeyError","error_message":"'ED'","traceback":"Traceback (most recent call last):\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/middleware/cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/fastapi/routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"/home/makeratl/AppWork/brewtalk/tts_api_server.py\", line 157, in text_to_speech\n  File \"/home/makeratl/AppWork/brewtalk/venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py\", line 309, in tts\n    speaker_id = self.tts_model.speaker_manager.name_to_id[speaker_name]\nKeyError: 'ED'\n"}